AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Kubernetes Native Secrets in AWS

Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  SecretsFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: secrets
      Runtime: go1.x
      Tracing: Active
      Events:
        Mutate:
          Type: Api
          Properties:
            Path: /secrets
            Method: POST
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - secretsmanager:CreateSecret
              Resource:
              - '*'
  PodsFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: pods
      Runtime: go1.x
      Tracing: Active
      Events:
        Mutate:
          Type: Api
          Properties:
            Path: /pods
            Method: POST
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - secretsmanager:GetSecretValue
              Resource:
              - '*'
Outputs:
  WebhookEndpoint:
    Description: "The Webhook HTTP API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"